/*
FILE para manejo de errores:
- IMAGENES ROTAS
- RESPUESTAS VACIAS (FORMULARIOS)
- ERRORES API
- FORMULARIOS INCOMPLETOS
feedback al usuario soibre:
-ERRORES PRESENTADOS
-ELIMINACION REALIZADA
-EDICIÓN REALIZADA
-CREACIÓN EXITOSA
*/